### ISSUE TITLE
MD:A tag

### ISSUE THREAD

**Issue by caleblareau** [FelixKrueger/SNPsplit#18]
Hi @FelixKrueger,

Great tool; quick question-- I get some reads with a `MD:A` tag (see attached .bam file), which causes SNPsplit to fail. My understanding though is that one could still use this tag as it specifies a character instead of a string:
https://samtools.github.io/hts-specs/SAMv1.pdf

Any thoughts to change the regex to include MD:A: tags? 
https://github.com/FelixKrueger/SNPsplit/blob/7bed7b64877986d9de599244a27c87a3d66a146e/SNPsplit#L236

On this note, I think that a more-graceful bow-out would be just leaving reads without an MD:Z tag as unassigned rather than killing the whole script. I don't know if you have thoughts on this? 

Thanks,
-Caleb

**Comment by caleblareau** [comment]
Sample `.bam` here: https://file.town/download/slqxuvq0j1iidwthmin8pwauj

**Comment by caleblareau** [comment]
Difference between MD:A and MD:Z on page 7 of the samtools pdf

<img width="839" alt="md" src="https://user-images.githubusercontent.com/16229089/37504448-c913834c-28b4-11e8-95aa-dd2404169a61.png">

**Comment by FelixKrueger** [comment]
Hi Caleb,

That sounds like a reasonable idea, I can probably take a look at this next week. Which aligner are you using, out of interest?

I am afraid the test file you linked comes up with videos of ladies who don't seem to be appropriately dressed for this time of year, and lots of "access blocked" warnings. I could provide you with a link to an FTP site to upload the file if that would help? In addition, I would also need a SNP file which you are using for the the SNPsplit process.

**Comment by caleblareau** [comment]
Yeesh, sorry about the link... I didn't see any suspicious behavior from my end; that's quite embarrassing. 

Here's a google drive link: https://drive.google.com/file/d/1pDl6seq6k_bIWyzKNVGz5r866FUWr5md/view?usp=sharing

I'm using `bowtie2` with a `-X 2000` flag, which I think is the only reason that I can align some small fragments (8, 9 bp). These come from the fact that I'm parsing out some scATAC-seq data where one read is heavily barcoded, and after trimming it, can be quite small. However, the paired read is still 36 bp, so I suspect bowtie2 is able to figure out how to align these very short reads when they arise. Note, though, these are exceptions and not the rules. 

Thanks again!

**Comment by FelixKrueger** [comment]
Hi Caleb,

That link worked much better.... I managed to download the BAM file (you didn't supply a SNP file though) and had a quick look. There was indeed one read which had an `MD:A` tag but no `MD:Z:` tag. I also noticed that you used Bowtie2 version `2.2.2` which is nearly 4 years old! Would you mind upgrading Bowtie2 to see if the problem still exists (which I doubt it does). I would like to avoid chasing red herrings that might have been fixed on the Bowtie2 side years ago. Cheers, Felix

**Comment by FelixKrueger** [comment]
Is there any update on this?

**Comment by FelixKrueger** [comment]
Assuming this has been fixed.
