### ISSUE TITLE
question regarding the HiC module

### ISSUE THREAD

**Issue by vivekbhr** [FelixKrueger/SNPsplit#23]
Hi @FelixKrueger 

Could you please tell me a bit about the format of the BAM files that you need in snpsplit for read sorting from HiC data? HiCUP manual is not clear about the output BAM, but I am assuming that 

1) It maps the R1 and R1 seperately using bowtie/bowtie2
2) removes invalid HiC pairs
3) Interleaves the R1 and R2  from valid pairs and write the `sample1_2.bam`, which can be taken by snpsplit

In that case I could in principle just map my R1 and 2 seperately using bowtie2, then interleave the output files, and this should serve as valid input for snpsplit. Am I correct?

Thanks,
Vivek

**Comment by FelixKrueger** [comment]
Hi Vivek,

Yes I think the output from HiCUP is a BAM file where R1 and R2 follow each other in consecutive lines. If you arrive at a similar file by whatever method and specify `--hic` in SNPsplit, I don't see why it wouldn't work in the very same way.

**Comment by vivekbhr** [comment]
Hey Phil. So we tested with raw bowtie mapping and it works as long as both reads are mapped and alignments are interleaved. Thanks!

**Comment by FelixKrueger** [comment]
Excellent! Phil :P
