### ISSUE TITLE
SNP value column in input snp file correspond to which information in vcf format files?

### ISSUE THREAD

**Issue by brainfo** [FelixKrueger/SNPsplit#35]
What does the SNP value mean?
![image](https://user-images.githubusercontent.com/11832080/83106485-1fd67e00-a0ef-11ea-832c-4a3b385cc7fb.png)
Does it mean "QUAL" in vcf files or any else information?

**Comment by FelixKrueger** [comment]
I think originally this would indicate whether the SNP was on the top or bottom strand. I think the value is always `1` as the SNPs output by SNPsplit are always relative to the top strand, so bottom line: you can safely just ignore this column.
