### ISSUE TITLE
'S' CIGAR operation not allowed

### ISSUE THREAD

**Issue by brainfo** [FelixKrueger/SNPsplit#36]
I aligned reads using Bowtie2, and when SNPsplit read the bam file, it said: `Found CIGAR operations other than M, I, D or N: 'S'. Not allowed at the moment`
Should I specify any parameter when running Bowtie2 or filter the input reads in some reads to rule out "S" type reads?
Could I just filter the sam file to get alignments other than 'S' alignments?  Does this differ with specify `
--end-to-end.
` when using Bowtie2?

**Comment by FelixKrueger** [comment]
The current released version does indeed not allow reads to be soft-clipped, `--end-to-end` would be better. I have in the meantime added support for softclipping as well though, but it is still in the development version. You could try to clone it with `git@github.com:FelixKrueger/SNPsplit.git`, and give that a go?

**Comment by FelixKrueger** [comment]
> The current released version does indeed not allow reads to be soft-clipped, `--end-to-end` would be better. I have in the meantime added support for softclipping as well though, but it is still in the development version. You could try to clone it with `git clone git@github.com:FelixKrueger/SNPsplit.git`, and give that a go?

**Comment by brainfo** [comment]
> The current released version does indeed not allow reads to be soft-clipped, `--end-to-end` would be better. I have in the meantime added support for softclipping as well though, but it is still in the development version. You could try to clone it with `git@github.com:FelixKrueger/SNPsplit.git`, and give that a go?

Ok, I'll have a try. Thanks!

**Comment by FelixKrueger** [comment]
I hope it worked?
