### ISSUE TITLE
PrepareGenome input

### ISSUE THREAD

**Issue by nservant** [FelixKrueger/SNPsplit#39]
Hi,
Idea of improvment ;
Would be great if SNPsplit_genome_preparation could either take a folder or a fasta file directly in input.
Cheers
N

**Comment by FelixKrueger** [comment]
Can I quickly follow this up. At the moment, you specify a folder and the genome preparation will then try to identify .fa files within that folder. Are you suggesting an option to specify a `.fa` file directly (presumably to avoid confusion if there are several different files in a folder?).

I'd be reluctant to change this behaviour to be honest as I'd like to keep it consistent across the various programs that handle it this way (e.g. `Bismark`, `coverage2cytosine`, `bam2nuc`, `reStrainingOrder` etc...). Would you agree?

**Comment by nservant** [comment]
ok I understand. That's fine.
N
