### ISSUE TITLE
SNP removal in Bismark

### ISSUE THREAD

**Issue by pubudumanoj** [FelixKrueger/SNPsplit#40]
Hi Felix,
I wanted to know how Bismark handle positions with SNPs. I am planning to remove SNPs (C to T) in each sample after identifying them with BIS-SNP. I want to know whether Bismark infer the actual methylation proportion at these genomic positions and therefore no need to remove them. But as I understood by reading the issue #17  we need to remove them. Am I correct?
Thank You

PS: Sorry I just noticed that I have added this issue to SNPsplit, not Bismark. But I cannot delete it now.

**Comment by FelixKrueger** [comment]
Cross posted, will reply on the Bismark-end.
