### ISSUE TITLE
The awk script makes me confused

### ISSUE THREAD

**Issue by lyhonk** [FelixKrueger/SNPsplit#5]
I think the awk script you given has some mistakes
`awk '{if($1 ~ "^#") {gsub("contig=<ID=", "contig=<ID=chr"); gsub("contig=<ID=chrMT", "contig=<ID=chrM"); print} else gsub("^MT", "M"); print "chr"$0}' mgp.v5.merged.snps_all.dbSNP142.vcf`
I think this script should be this
`awk '{if($1 ~ "^#") {gsub("contig=<ID=", "contig=<ID=chr"); gsub("contig=<ID=chrMT", "contig=<ID=chrM"); print} else {gsub("^MT", "M"); print "chr"$0}}' mgp.v5.merged.snps_all.dbSNP142.vcf`
my system is centos 7

**Comment by FelixKrueger** [comment]
Thanks for the pointer, I've added the squiggly brackets.
