### ISSUE TITLE
Using the --full_sequence genome

### ISSUE THREAD

**Issue by ezecalvo** [FelixKrueger/SNPsplit#51]
Hi,

I created a hybrid genome using the --full_sequence option to avoid masking and get a higher mapping accuracy. Nevertheless, 100% of my reads are unassignable after mapping because there are no Ns, which makes perfect sense. 

What's the point of having the --full_sequence option if you can't split reads to alleles after? Is it just a SNPsplit feature to create a new genome?

Thanks!

**Comment by FelixKrueger** [comment]
Indeed, it is just to create new genomes (sometimes you might want to extract FastA sequence and look at them side-by-side); it is also required as the new reference genome in case you are generating dual strain hybrids.

**Comment by ezecalvo** [comment]
Got it, thanks!
