### ISSUE TITLE
Which reference genome I have to use it for genomepreparation

### ISSUE THREAD

**Issue by luckysardar** [FelixKrueger/SNPsplit#54]
Greetings..,
Nice tool I wanted use SNP split in my chipseq data I am new to this tool Can you please suggest me which reference file I can use here I have downloaded the vcf file v5 from the Sanger database as mentioned in user guide and reference genome from the ensemble GRCm39  latest version with GTF. 

Can you please suggest can I proceed with the genome preparation or please suggest link to download reference genome and GTF  it will be very helpful

Thank you

**Comment by luckysardar** [comment]
Hello can you please suggest me...

Thank you

**Comment by FelixKrueger** [comment]
Sorry for the late response (it turns out that Wales is truly off-grid :)).

The Mouse Genomes Project v5 file requires the GRCm38 genome build (ftp://ftp.ensembl.org/pub/release-102/fasta/mus_musculus/dna/).

**Comment by luckysardar** [comment]
Thank you for the reply but in VCF file reference mentioned as below comment so I am bit confused 
can you please clarify
##reference=ftp://ftp-mouse.sanger.ac.uk/ref/GRCm38_68.fa

**Comment by FelixKrueger** [comment]
The important part is that you get the GRCm38 reference sequence. This sequence has not changed since the day it was released. The things that did change are the annotation releases (in your case the _68, I think right now it is >100), however this never affects the DNA sequence itself. Just make sure it is not NCBIM37 or GRCm39.

**Comment by luckysardar** [comment]
Thank you for the quick reply,
Okay In case of GTF which file I have use? below link will work?
[GRCm38_102](http://ftp.ensembl.org/pub/release-102/gtf/mus_musculus/)

**Comment by FelixKrueger** [comment]
The GTF file you are going to use might affect your downstream analysis, but will have nothing to do with the SNPsplit processing itself. So yea, the more recent the better I guess?

**Comment by luckysardar** [comment]
Okay Felix your sggestions will be very helpfull I am using same annotation file for all my analysis RNA and Chip seq so I am believing it will not effect much in my analysis

Thank you.,
