### ISSUE TITLE
Two much variation in the Two strain specific reads percentage

### ISSUE THREAD

**Issue by luckysardar** [FelixKrueger/SNPsplit#57]
Hi Felix,

I am getting too much variation read assignment in my analysis this. Thread is from after resolving my issue. [https://github.com/FelixKrueger/reStrainingOrder/issues/2](url) same problem observed in snpsplit that's why I asked again here. Can you please confirm modification needed here ... 11-13% and 50-60% JF1 and 129s1 respectively I am using Vcf v7 please suggest me. for the data which I have is pure hybrid strain confirm this wetlab person several times. I have another dataset with the different strain cross C57 vs 129S1 there I am not facing any issue. 

please help me 

Thank you

**Comment by FelixKrueger** [comment]
I have just indexed a 129S1/JF1 (v7) dual hybrid strain, aligned the test data that was mentioned in the reStrainingOrder issue, and got the following results:

<img width="1109" alt="Screenshot 2022-03-28 at 10 49 22" src="https://user-images.githubusercontent.com/5870509/160372895-fd693e2a-122d-43ca-a773-d901734a42c0.png">

What this shows is that there is again a roughly 70:30 split for 129S1/JF1, which is largely agreeing with the results of reStrainingOrder. Just to confirm: though conceptually similar, the exact methodology of `SNPsplit` and `reStrainingOrder` is completely separate and independent of each other. The results of reStrainingOrder are solely based on SNP positions on chromosome 1 where strains, here 129S1 and JF1, are distinct from each other. SNPsplit works genome-wide and was performed on all N-masked dual hybrid positions, using read-pairs.

Even if the experimentalist confirms that you should have a 'clean' 50:50 F1 hybrid, the data you presented tells a somewhat different story (it might e.g. agree better with a scenario where a pure 129S1 line was crossed with a 129S1/JF1 hybrid....)
