### ISSUE TITLE
Using SNPsplit to analysis Bisulfite-Seq data in plant

### ISSUE THREAD

**Issue by GatorShan** [FelixKrueger/SNPsplit#58]
Dear Felix,

I am wondering if SNPsplit could be used to analyze Bisulfite-Seq data in plants? Or is SNPsplit designed for data analysis in mammalian systems?

I am asking this question because plant DNA methylation occurs in all cytosine sequence contexts: CG, CHG, and CHH. In contrast, mammalian DNA methylation is located almost exclusively in the CG context. If SNPsplit considers CG methylation only, SNPs of cytosine at CHG/CHH contexts can't be differentiated between a real SNP and methylation state. Does this make sense?

Thank you so much for your help!

Best,

Shan

**Comment by FelixKrueger** [comment]
Dear Shan,

SNPsplit doesn't take the sequence context into account for deciding whether or not a position can be used. So in that sense, it does not preferentially treat mammalian data over any other data, including plants.

As is laid out in the User manual, SNPsplit is intended for use with mouse cell lines where both paternal genomes are fully known. If you have such in situation for the plants you are looking at then you should be able to use SNPsplit for your purposes as well. This has come up a number of times, you might want to take a look at closed issues (here is for example https://github.com/FelixKrueger/SNPsplit/issues/45).

**Comment by GatorShan** [comment]
Dear Felix,

Thanks for your quick response and explanation! This makes sense.

Best,

Shan
