### ISSUE TITLE
single-end mode does not work

### ISSUE THREAD

**Issue by shanwai1234** [FelixKrueger/SNPsplit#61]
Hi authors,

I tried to run SNPsplit using the command ```SNPsplit --snp_file <SNP_file> <bam file>```, but it gives me the error ```Unable to detect library type automatically, please specify whether the file is single- or paired-end manually```. I tried to give the command of ```--single_end``` or ```--single-end```, but none of them works. Could you give me any suggestions on which command I should use to specify the single-end mode? Thanks!

**Comment by FelixKrueger** [comment]
Hi, an option `--single_end` has been added only fairly recently (see https://github.com/FelixKrueger/SNPsplit/blob/master/CHANGELOG.md#v050dev). So could you clone the the latest development version and try again?

**Comment by shanwai1234** [comment]
yep, it works, thanks @FelixKrueger !
