### ISSUE TITLE
How to phase Hi-C data using SNPs

### ISSUE THREAD

**Issue by hmyh1202** [FelixKrueger/SNPsplit#63]
Hello:

 In your wiki, Hi-C data must be produced by HICUP ? 

 How about HiCpro software ？

The Best . Thank you !

**Comment by FelixKrueger** [comment]
To be completely honest I don't know if it would work with HiCpro data. All I could find about the specific requirements for Hi-C was that R1 and R2 (the bait and prey/other end or whatever you want yo call it) follow each other on consecutive lines in the BAM file (see here: https://github.com/FelixKrueger/SNPsplit/blob/master/SNPsplit_User_Guide.md#hi-c-data). Maybe it is just worth a shot?

**Comment by hmyh1202** [comment]
OK, fine, I will try it, thank you.
