### ISSUE TITLE
single end mode not working

### ISSUE THREAD

**Issue by rberrens** [FelixKrueger/SNPsplit#66]
When I try to run SNPsplit in single end mode it gives me the following error: SNPsplit --single_end --snp_file <SNP_FILE> <INPUT.bam>
Unknown option: single_end
Please respecify command line options

If I add nothing to autodetect it says: Testing if input file 'Aligned.out.bam' looks like a Bisulfite-Seq file
Unable to detect library type automatically, please specify whether the file is single- or paired-end manually

If I run the same forcing it to be paired SNPsplit is running.

**Comment by FelixKrueger** [comment]
Hi Rebecca,

The option `--single_end` has been added very recently: https://github.com/FelixKrueger/SNPsplit/blob/master/CHANGELOG.md#v050dev. If you do:

```
git clone git@github.com:FelixKrueger/SNPsplit.git
```

it should start working.

**Comment by rberrens** [comment]
thank you Felix!
