### ISSUE TITLE
Using SNPsplit for single cell data

### ISSUE THREAD

**Issue by taolin1994** [FelixKrueger/SNPsplit#69]
Given cellranger is based on STAR a software supported by SNPsplit, I try to use SNPsplit v0.5.0 to deal with 10X scRNAseq data.  First, I builded a N-maked genome using SNPsplit_genome_preparation.  Then, I run cellranger pipeline (mkref and count) using the N-maked genome in cellranger v7.0.0, resulting in a BAM file.  I tried to split the BAM file using SNPsplit v0.5.0；however, no reads were mapped to genome1 and genome2.  

I am not sure what I did was right. Can SNPsplit handle 10X  scRNAseq data? Do you have any suggestions or comments?

Thank you! 

Lin

**Comment by FelixKrueger** [comment]
That is a very interesting question! I have never tried this myself, but I would assume that the STAR mapped data produced by CellRanger could in theory be split allele-specifically, but there are some considerations:

- data aligned with STAR needs to be run with a few extra parameters (outlined https://github.com/FelixKrueger/SNPsplit/blob/master/SNPsplit_User_Guide.md#rna-seq-alignments-with-star), in particular with `--outSAMattributes NH HI NM MD`. I am not sure if one can modify the command for STAR that CellRanger uses internally?
- If we assume that your data is from a hybrid strain, and you get the allele-specific sorting to work, you might face the issue that you will have allele-specific reads, but you would need to assign these reads back to individual single cells...

Just as a heads up, I will be on leave for some time now and will most likely not respond to any queries until my return. Wishing you good luck in the meantime!
-

**Comment by taolin1994** [comment]
Thank you very much for your prompt response!

According to your suggestion, I have tried to analyse my F1 scRNA-seq data using STAR V2.7.10. I am glad  to tell you that the BAM  file produced by STAR could be split by SNPsplit in spite of a low mapping rate to genomes 1 and 2 (4.23% and 3.86% in my data).  Unfortunately, these BAM files from STAR or SNPsplit could not be further processed by STAR. I get the following error tips:

EXITING because of FATAL ERROR in reads input: short read sequence line: 0
Read Name=@ 
Read Sequence=""
DEF_readNameLengthMax=50000
DEF_readSeqLengthMax=650

Aug 20 21:45:43 ...... FATAL ERROR, exiting

Alex indicates some problem with formatting of the fastq files (https://github.com/alexdobin/STAR/issues/493), but I haven't solved it yet. This problem may be beyond the scope of SNPsplit. Anyway, I am happy to share my experience.  Any suggestions or comments are welcomed.

Lin

**Comment by FelixKrueger** [comment]
Good news. The relatively low rate of allele specific reads can be explained by the fact that 10X is single end sequencing, and theoretically only covers the 3' end of transcripts....

I am currently on holiday, but I might reply in more detail upon my return. I'd be happy to hear how you are solving your formatting issue (not quite sure what the problem is as SNPsplit doesn't produce any FastQ files at all...). Cheers, Felix
________________________________

**Comment by taolin1994** [comment]
I'm sorry to disturb your holiday.  I am glad to tell you that I have solved this problem by adjusting some parameters in STAR.  Now the mapping rates of my 10X data are ~9% and ~10%. I tend to believe that the result may be normal and helpful. Thanks for your great tool!

Have a good time.

Lin

**Comment by ziyuan-ma** [comment]
> I'm sorry to disturb your holiday. I am glad to tell you that I have solved this problem by adjusting some parameters in STAR. Now the mapping rates of my 10X data are ~9% and ~10%. I tend to believe that the result may be normal and helpful. Thanks for your great tool!
> 
> Have a good time.
> 
> Lin

Hi Lin, thanks for sharing your experience with separating scRNA-seq data using SNPsplit. I’m currently facing the same low mapping rate issue (0.02% for genome 1 and 1.70% for genome 2) and was wondering if you could share the parameters you adjusted in STAR to improve mapping. Thanks a lot!

Ziyuan

**Comment by taolincj** [comment]
Hi, Ziyuan. That's a long way off.  I run STAR with following parameters:
`STAR --runThreadN 10 --genomeDir starN2.7.10 \`
`--readFilesCommand zcat \`
`--readFilesIn $read2 $read1 \`
`--outFileNamePrefix ./$sample/ \`
`--outSAMattributes NH HI NM MD CB CR UB CY UR UY \`
`--alignEndsType EndToEnd \`
`--outSAMtype BAM SortedByCoordinate \`
`--soloType CB_UMI_Simple --soloCBwhitelist $whitelist --soloCBstart 1 --soloCBlen 16 --soloUMIstart 17 --soloUMIlen 10 --soloUMIdedup 1MM_All --soloBarcodeReadLength 150 \`
`--soloOutFileNames Solo.out/ features.tsv barcodes.tsv matrix.mtx`

I hope it is helpful.
Lin Tao

**Comment by FelixKrueger** [comment]
Thanks for chipping in!
