### ISSUE TITLE
minimap2

### ISSUE THREAD

**Issue by kullrich** [FelixKrueger/SNPsplit#70]
Hi,

is SNPsplit incompatible to minimap2, as it is mentioned that bwa is not compatible?

Thank you in anticipation

Best regards

Kristian

**Comment by FelixKrueger** [comment]
Hi Kristian,

I don't think I have tested this myself yet, the basic requirements would be that minimap2 outputs the required SAM tags, and that it doesn't assign a random base whenever it encounters an 'N' in the reference sequence.

An additional complication might be that SNPsplit counts the number of calls that were found for allele1 and allele2, and as soon as it detects both of them within the same read (or read pair) the read (or read pair) is considered conflicting  - and is thus ignored. I would imagine that such a scenario would increase by a fair amount if you have very long reads... 

Having said that, it might be worth a shot?

**Comment by FelixKrueger** [comment]
Closing this for the time being.

**Comment by CWYuan08** [comment]
Dear @kullrich @FelixKrueger,

I'm wondering if you have an updated view on this? I would like to run SNPsplit with some ONT aligned cDNA data. 

Thank you very much!

Best,
CW

**Comment by FelixKrueger** [comment]
I haven't followed this in any detail I am afraid.
