### ISSUE TITLE
Tutorial for SNPsplit

### ISSUE THREAD

**Issue by yonniejon** [FelixKrueger/SNPsplit#73]
Hi,

I apologize if this question is naive and it is due to not having read the user-guide enough but I am confused about how to use SNPsplit. From what I understand there are two commands: `SNPsplit_genome_preparation` and `SNPsplit`. The user guide describes the format of the input files it expects. But I think it would help if there was a simple tutorial which shows the flow. I guess the output files of `SNPsplit_genome_preparation` are meant to be input files to `SNPsplit` ? I am guessing the file that is meant to be used as the `--snp_file` for `SNPsplit` command is the `all_{strain 2}_SNPs_{strain 1}_reference.based_on_{ref}.txt` file that was output by the  `SNPsplit_genome_preparation` command? I see that it has the same format except in the user guide it shows a header line. Will there be a difference which strain is used as the reference/strain 1?

**Comment by FelixKrueger** [comment]
Hi @yonniejon 

Thanks for your comments. I am currently in the process of updating SNPsplit and its documentation to the new v8 release of the Mouse Genomes project; I am also going to take a look at the sections you found confusing to see if they can be clarified further.

Generally, genome 1 will be the reference (REF) strain, and genome 2 is the alternative (ALT) strain. For dual hybrids, the strain selected with `--strain` is considered to be the new REF, `--strain2` if the new ALT.

**Comment by FelixKrueger** [comment]
I have now updated the SNPsplit documention to mkdocs and the GRCm39 genome build (with version 8 annotations): http://felixkrueger.github.io/SNPsplit/

I have also added a tab with an overview of the workflow. I realise that this isn't quite a step-by-step tutorial, but we could add this easily should it be required. I hope you'll like it.
