### ISSUE TITLE
Bowtie1 as  the   aligner of  Bismark

### ISSUE THREAD

**Issue by lelesama** [FelixKrueger/SNPsplit#76]
Hello 

SNPsplit_User_Guide  suggested the resulting .fa files are ready to be indexed with aligners including Bowtie2, Tophat, STAR, HISAT2, HiCUP and Bismark.

Could I use  Bowtie1 as  the   aligner of  Bismark?

**Comment by FelixKrueger** [comment]
No, I am afraid Bowtie 1 is:
- a) not capable of aligning to N-masked genomes, and
- b) no longer supported by Bismark as of 2019 or so
